export const recipes = [{ id: 'wellness', name: 'Still — small rituals, better days', description: 'An editorial wellness companion with daily rituals, habit detail, and weekly progress.', routes: [{ path: '/', title: 'Today' }, { path: '/habit', title: 'Morning ritual' }, { path: '/progress', title: 'Your progress' }] }] as const;
export const presetNames = ['sage', 'clay', 'midnight'] as const;
const foundations = { radius: 24, spacing: 8, bodySize: 16, titleSize: 36, elevation: 0 };
export const presets = {
  sage: {
    light: { ...foundations, background: '#F5F5EF', surface: '#FFFFFF', text: '#213B30', muted: '#657266', accent: '#355E45', onAccent: '#FFFFFF', border: '#DDE2D7' },
    dark: { ...foundations, background: '#14231C', surface: '#203329', text: '#F0F3E9', muted: '#A8B9A8', accent: '#BFDC9C', onAccent: '#172A1D', border: '#3A4C3F' },
  },
  clay: {
    light: { ...foundations, radius: 16, background: '#FBF3EC', surface: '#FFFCF8', text: '#492F2B', muted: '#85645C', accent: '#9B4E39', onAccent: '#FFFFFF', border: '#E9D6C9' },
    dark: { ...foundations, radius: 16, background: '#2B201D', surface: '#3C2C26', text: '#FFF2E6', muted: '#D2B4A5', accent: '#F0AD8E', onAccent: '#35221B', border: '#64473D' },
  },
  midnight: {
    light: { ...foundations, radius: 28, background: '#F1F2FA', surface: '#FFFFFF', text: '#262940', muted: '#646781', accent: '#5357A2', onAccent: '#FFFFFF', border: '#DCDDED' },
    dark: { ...foundations, radius: 28, background: '#191B2D', surface: '#252840', text: '#F2F1FF', muted: '#B0B1CE', accent: '#BABDF9', onAccent: '#232444', border: '#414563' },
  },
};
export const guidance = `Build real Expo Router screens using src/ui and src/theme/design.json. Keep hierarchy deliberate: one primary action, generous whitespace, short readable headings. Use semantic tokens, minimum 44-point touch targets, labeled controls, safe areas, and native components. For React Native Web, expose interactive state with explicit supported aria-checked, aria-selected, aria-current and aria-valuemin/max/now props; accessibilityState and accessibilityValue alone may not reach the DOM. Keep native semantics as appropriate and verify the rendered states with keyboard and accessibility checks. Preserve loading, empty and error states. Describe the brief and screen map before editing. Inspect revisions before writes. Use a periodic screenshot → inspect → adjust → recapture loop, not a final-only screenshot pass. Call preview_capture after the first renderable screen, after each meaningful layout/style/image/navigation change or small UI batch, and before handoff. Capture each changed route at compact and large sizes, inspect screenshots and diagnostics, then refine. At the first capture, verify that the harness delivers the actual PNG to the model: identify specific visible details only if the image is genuinely visible. Metadata, base64 text, a saved file, OCR, and DOM geometry alone do not prove visual inspection. If image delivery fails, use a supported image viewer or attachment; otherwise report visual review blocked and ask for human review in Studio while continuing nonvisual checks. Never claim to have seen an image that was not visible. Inspect hierarchy, typography, spacing, contrast, image cropping, clipping, safe areas, primary actions and navigation. Make a focused fix based on an observed issue. After a visual refinement, recapture the same route at the same viewport and appearance before claiming improvement; a larger viewport does not prove a compact-layout fix. Also match content/state and scroll position; preview_capture uses a fresh browser context, not Studio's transient state. Record capture IDs, actual visual observations, edits and remaining limitations. A Studio capture is not automatically pushed to the agent: request images through MCP. Keep screenshot image content intact through any adapter instead of forwarding only structured metadata. Distinguish controls visible without scrolling from controls reachable by scrolling, and verify interactions separately. Report only completed tool results; a client approval denial is a blocker, not a successful edit or permission to bypass approval. Web captures do not establish native correctness. Never add a dependency without explicit operator review.`;
