import { McpServer, ResourceTemplate } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { z } from 'zod';
import type { Engine } from '../../core/src/engine.js';
import { registerBackendTools } from './backend-actions.js';
import { captureRouteSchema, createSchema, errorResult, previewTransportInput, routeSchema, viewportSchema, writeSchema } from '../../core/src/contracts.js';
import { testingGuide } from '../../core/src/testing-guide.js';
import { nativeBuildApplyInput, nativeBuildConfiguration, nativeBuildGuide } from '../../core/src/native-builds.js';
import { workspaceActionInput, workspacePrepareInput, workspaceRemoveInput, workspaceSelection } from '../../core/src/native-workspace-contracts.js';
import { deliverySelection, deliveryBuildInput, deliveryActionInput, deliveryInstallInput, deliveryLaunchInput, deliveryRemoveInput } from '../../core/src/native-delivery-contracts.js';
import { designUpdateSchema } from '../../core/src/design.js';
import { studioControlSchema } from '../../core/src/studio-contracts.js';
import { applyInspectorSetup, previewInspectorSetup, inspectorApplySchema } from '../../core/src/preview-inspector.js';
import { guidance, presets, recipes } from '../../templates/src/catalog.js';
import { approveAssetSchema, briefUpdateSchema, importBase64Schema, transformSchema } from '../../core/src/media-contracts.js';
import { jobRequestSchema } from '../../core/src/media-job-contracts.js';
import { iconApplySchema, iconCheckSchema, iconPrepareSchema, iconPreviewSchema } from '../../core/src/icon-contracts.js';
import { kitFileIdSchema, launchKitCreateSchema, launchKitRemoveSchema, type LaunchKit } from '../../core/src/launch-kit-contracts.js';

const projectId = z.uuid();
const text = (value: Record<string, unknown>): CallToolResult => ({ content: [{ type: 'text', text: JSON.stringify(value) }], structuredContent: value });
async function guardedResult(operation: () => Promise<CallToolResult>): Promise<CallToolResult> {
  try { return await operation(); } catch (error) { return { ...text(errorResult(error)), isError: true }; }
}
const annotations = (readOnlyHint: boolean, destructiveHint = false) => ({ readOnlyHint, destructiveHint, idempotentHint: readOnlyHint, openWorldHint: false });
export function registerBuiltinTools(server: McpServer, engine: Engine) {
  const guarded = (operation: () => Promise<CallToolResult>) => guardedResult(async () => { const result = await operation(); await engine.projects.flushState(); return result; });
  registerBackendTools(server, engine);
  server.registerTool('native_delivery_preflight', { description: 'Inspect local Xcode, CocoaPods, paired physical iPhones and available Apple Development signing teams. No build, account login or phone changes. Local Studio only.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => { await engine.projects.get(projectId); return text(await engine.nativeDeliveries.preflight()); }));
  server.registerTool('native_delivery_plan', { description: 'Review a local iOS Release build from a ready Preview/No backend preparation, selecting an exact iPhone and signing team. Includes Apple automatic provisioning effects. No build or installation.', inputSchema: { projectId, selection: deliverySelection }, annotations: annotations(true) }, ({ projectId, selection }) => guarded(async () => text(await engine.nativeDeliveries.plan(projectId, selection))));
  server.registerTool('native_delivery_build', { description: 'Start the reviewed local iOS Release build with execution trust and human confirmation. Downloads native dependencies and runs Xcode automatic signing; may register this app/device with Apple. Stable requestId prevents replay. Poll native_delivery_list. Does not install or publish.', inputSchema: { projectId, input: deliveryBuildInput }, annotations: { ...annotations(false), openWorldHint: true } }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.build(projectId, input))));
  server.registerTool('native_delivery_list', { description: 'Read durable local native build, signed artifact, install and launch receipts. Interrupted operations are never replayed. Launch is not proof of visual correctness. No private compiler logs or arbitrary paths.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text({ deliveries: await engine.nativeDeliveries.list(projectId) })));
  server.registerTool('native_delivery_install_plan', { description: 'Verify the signed artifact and selected iPhone, and review whether installation will replace an existing app. Requires current delivery revision. No phone changes.', inputSchema: { projectId, input: deliveryActionInput }, annotations: annotations(true) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.installPlan(projectId, input))));
  server.registerTool('native_delivery_install', { description: 'Install exactly the reviewed signed app on the selected physical iPhone with human confirmation. Can replace an existing app with this identifier as disclosed by install_plan. Poll receipts; failure can have an uncertain device outcome. Does not launch or publish.', inputSchema: { projectId, input: deliveryInstallInput }, annotations: { ...annotations(false, true), openWorldHint: true } }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.install(projectId, input))));
  server.registerTool('native_delivery_launch', { description: 'Open the verified installed app on its selected iPhone with human confirmation. Restarts only this app if already running. Reports the OS process ID; still check the screen and interactions on the phone.', inputSchema: { projectId, input: deliveryLaunchInput }, annotations: { ...annotations(false), openWorldHint: true } }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.launch(projectId, input))));
  server.registerTool('native_delivery_cancel', { description: 'Cancel an owned active local Xcode build using the current revision. Retains the isolated build copy; does not undo provisioning, uninstall apps or stop unrelated processes.', inputSchema: { projectId, input: deliveryActionInput }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.cancel(projectId, input))));
  server.registerTool('native_delivery_remove', { description: 'Remove only the reviewed terminal local build and its retained artifact using its current revision and human confirmation. Does not uninstall the phone app, revoke signing or change the original app source.', inputSchema: { projectId, input: deliveryRemoveInput }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeDeliveries.remove(projectId, input))));
  server.registerTool('native_workspace_plan', { description: 'Review bounded immutable app/assets, pinned dependencies and explicit public backend for isolated native preparation. Requires saved app build identity; custom profiles/clients are rejected. Read-only; returns fingerprints, file manifest, overlays and consequences.', inputSchema: { projectId, selection: workspaceSelection }, annotations: annotations(true) }, ({ projectId, selection }) => guarded(async () => text(await engine.nativeWorkspaces.plan(projectId, selection))));
  server.registerTool('native_workspace_prepare', { description: 'Prepare the exact reviewed workspace with human confirmation and execution trust. Copies source, installs pinned dependencies and validates TypeScript/web/native JavaScript exports in a separate directory. Does not sign, upload or submit a build. Use a stable requestId; repeated IDs never rerun work.', inputSchema: { projectId, input: workspacePrepareInput }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeWorkspaces.prepare(projectId, input))));
  server.registerTool('native_workspace_list', { description: 'Read durable preparation state, input identity and validation/export receipts for this app. Reconciles interrupted runtime records without rerunning preparation. No raw compiler output, provider credentials or arbitrary paths.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text({ workspaces: await engine.nativeWorkspaces.list(projectId) })));
  server.registerTool('native_workspace_cancel', { description: 'Cancel an owned active preparation with its latest record revision. Original source and preview are preserved; retained workspace cleanup is separate.', inputSchema: { projectId, input: workspaceActionInput }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeWorkspaces.cancel(projectId, input))));
  server.registerTool('native_workspace_remove', { description: 'Remove an explicitly reviewed terminal workspace and its JavaScript export artifacts with the latest revision. Refuses active jobs and replaced/symlinked directories. Does not delete the original app.', inputSchema: { projectId, input: workspaceRemoveInput }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeWorkspaces.remove(projectId, input))));
  server.registerTool('native_build_inspect', { description: 'Read local app build identifiers, Expo project link, dependency fingerprint, build prerequisites and user/agent instructions. Does not verify provider ownership or execute builds.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text(await engine.nativeBuilds.inspect(projectId))));
  server.registerTool('native_build_plan', { description: 'Review exact local app.json/eas.json build setup changes using user-supplied identifiers and optional existing Expo owner/project ID. Checks registered identity collisions and preserves custom profiles. Omit configuration to review interrupted-setup recovery. No provider calls or dependency installation.', inputSchema: { projectId, configuration: nativeBuildConfiguration.optional() }, annotations: annotations(true) }, ({ projectId, configuration }) => guarded(async () => text(await engine.nativeBuilds.plan(projectId, configuration))));
  server.registerTool('native_build_apply', { description: 'Apply the exact reviewed local native-build setup or recovery. Pass configuration and proposedRevision from native_build_plan with human confirmation. Stops preview; source and dependency changes invalidate the proposal. No account connection, signing, upload or build is performed.', inputSchema: { projectId, input: nativeBuildApplyInput }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.nativeBuilds.apply(projectId, input))));
  server.registerTool('project_list', { description: 'List remembered projects in this runtime workspace without executing app code.', inputSchema: {}, annotations: annotations(true) }, () => guarded(async () => text({ projects: await engine.projects.list() })));
  server.registerTool('project_open', { description: 'Remember an existing project by directory slug within the configured workspace, using its .mobile-builder.json. Does not execute code or import arbitrary directories. Select it with studio_control.', inputSchema: { slug: createSchema.shape.slug }, annotations: annotations(false) }, ({ slug }) => guarded(async () => { const project = await engine.projects.register(slug); engine.diagnostics.emit('change'); return text({ project }); }));
  server.registerTool('studio_inspect', { description: 'Read the shared Studio selected project, workspace, view routes/sizes, active view and revision. Preferences persist; no credentials or browser context are returned.', inputSchema: {}, annotations: annotations(true) }, () => guarded(async () => text(await engine.studio.snapshot())));
  server.registerTool('studio_control', { description: 'Revision-checked shared Studio control: select project; navigate Preview, Backend, Assets, App Icons, Activity or Settings; open Design/Launch Kit; switch All screens, Focus or Compare; focus-screen by route; compare screens or phone sizes; add/remove/activate/route/resize/reload live views (maximum two). Does not start a runtime, execute apps, approve spending, or expose credentials. Inspect again after conflicts.', inputSchema: studioControlSchema, annotations: annotations(false) }, input => guarded(async () => text(await engine.studio.control(input))));
  server.registerTool('activity_list', { description: 'Read project media-job activity and retained captures. Does not approve or run provider requests.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => { await engine.projects.get(projectId); const backend = await engine.backends.inspect(projectId); return text({ ...await engine.mediaJobs.list(projectId), captures: engine.captures.list(projectId), backend: { setup: backend.setup, operations: backend.operations.map(({ id, kind, state, environment, planHash, steps, error }) => ({ id, kind, state, environment, planHash, steps, error })) } }); }));
  server.registerTool('board_capture', { description: 'Refresh a saved screen in All screens using a fresh compact web capture. Keeps the latest image per route locally across restarts (up to 24); source edits mark it stale. Does not capture the visible iframe session or call a model.', inputSchema: { projectId, route: routeSchema }, annotations: annotations(false) }, ({ projectId, route }, extra) => guarded(async () => {
    const meta = await engine.boardCaptures.capture(projectId, route, extra.signal); engine.diagnostics.emit('change', projectId);
    const png = await engine.boardCaptures.get(projectId, meta.id);
    return { ...text(meta), content: [{ type: 'image', data: png.toString('base64'), mimeType: 'image/png' }, { type: 'text', text: JSON.stringify(meta) }] };
  }));
  server.registerTool('inspector_setup_preview', { description: 'Review exact development Inspector integration changes before applying. Does not write files.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text(await previewInspectorSetup(engine, projectId))));
  server.registerTool('inspector_setup_apply', { description: 'Apply a reviewed development Inspector integration proposal with confirmation and matching revision.', inputSchema: inspectorApplySchema, annotations: annotations(false, true) }, input => guarded(async () => { const result = await applyInspectorSetup(engine, input.projectId, input); engine.diagnostics.emit('change'); return text(result); }));
  server.registerTool('project_create', { description: 'Create an independent Expo wellness app. Does not install or execute code. Choose a unique directory slug.', inputSchema: createSchema, annotations: annotations(false) }, input => guarded(async () => text({ project: await engine.projects.create(input), nextActions: ['project_inspect', 'preview_start'], guidance })));
  server.registerTool('project_inspect', { description: 'Inspect scoped source, content revisions, design, routes, captures and preview status. Omit paths for metadata only.', inputSchema: { projectId, paths: z.array(z.string().max(240)).max(10).default([]) }, annotations: annotations(true) }, ({ projectId, paths }) => guarded(async () => text(await engine.inspect(projectId, paths))));
  server.registerTool('project_write_files', { description: 'Write up to 20 scoped text files. Read revisions first; expectedRevision=null means create only. Batch is prevalidated, not filesystem-transactional.', inputSchema: { projectId, writes: z.array(writeSchema).min(1).max(20) }, annotations: annotations(false, true) }, ({ projectId, writes }) => guarded(async () => text(await engine.files.write(projectId, writes))));
  server.registerTool('design_apply', { description: 'Update semantic tokens or preset with a required current design revision. A preset or mode change resets tokens to that preset.', inputSchema: { projectId, update: designUpdateSchema }, annotations: annotations(false, true) }, ({ projectId, update }) => guarded(async () => text(await engine.designs.apply(projectId, update))));
  server.registerTool('preview_start', { description: 'Install the pinned dependencies and start/reuse managed Expo. Requires operator --trust-execution. May take several minutes on first use. Not a sandbox.', inputSchema: { projectId }, annotations: { ...annotations(false), openWorldHint: true } }, ({ projectId }, extra) => guarded(async () => text(await engine.previews.start(projectId, extra.signal))));
  server.registerTool('preview_set_transport', { description: 'Start or switch the selected app preview between localhost and the local network for Expo Go phones. Requires trusted execution; LAN makes generated development code reachable on the local network. Read project_inspect.preview.sessionId first and pass it as expectedSessionId (null if stopped). Switching restarts preview and clears user-reported phone tests. No tunnel or phone detection. Read builder://guide for phone instructions.', inputSchema: { projectId, input: previewTransportInput }, annotations: { ...annotations(false), openWorldHint: true } }, ({ projectId, input }, extra) => guarded(async () => text(await engine.setPreviewTransport(projectId, input, extra.signal))));
  server.registerTool('preview_stop', { description: 'Stop this runtime’s owned preview process for the project.', inputSchema: { projectId }, annotations: { ...annotations(false), idempotentHint: true } }, ({ projectId }) => guarded(async () => { await engine.previews.stop(projectId); return text(engine.previews.status(projectId)); }));
  server.registerTool('preview_capture', { description: 'Capture an app path in a managed preview as React Native Web, not native proof. Simple screen parameters such as /lessons?lesson=0 are supported. Use after first render, meaningful UI changes and before handoff. Returns PNG image plus scoped artifact URI; inspect the actual image, not just metadata, then refine and recapture at the same route/size/state. Report visual review blocked if the harness cannot display images. Cross-origin requests and redirects are blocked.', inputSchema: { projectId, route: captureRouteSchema.default('/'), viewport: viewportSchema.default('compact') }, annotations: annotations(false) }, ({ projectId, route, viewport }, extra) => guarded(async () => {
    const { meta, png } = await engine.captures.capture(projectId, route, viewport, extra.signal);
    return { ...text({ ...meta, uri: `builder://projects/${projectId}/captures/${meta.id}` }), content: [{ type: 'image', data: png.toString('base64'), mimeType: 'image/png' }, { type: 'text', text: JSON.stringify(meta) }] };
  }));
  server.registerTool('project_diagnostics', { description: 'Read bounded install, preview, browser and builder diagnostics, including truncation indicators.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => { await engine.projects.get(projectId); return text(engine.diagnostics.read(projectId)); }));
  server.registerTool('icon_check', { description: 'Check an approved image for conservative Android adaptive foreground alpha/safe-zone suitability. Not native or artistic validation.', inputSchema: { projectId, input: iconCheckSchema }, annotations: annotations(true) }, ({ projectId, input }) => guarded(async () => text(await engine.appIcons.check(projectId, input.assetId))));
  server.registerTool('icon_prepare', { description: 'Create an immutable 1024px icon master or distinct transparent adaptive foreground candidate from an approved image. Review and approve the output; no config changes.', inputSchema: { projectId, input: iconPrepareSchema }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.appIcons.prepare(projectId, input))));
  server.registerTool('icon_preview', { description: 'Preview exact before/after app.json and revisions for approved icon assets. Display changes and warnings to the user before confirmation. Does not write config or execute dynamic config.', inputSchema: { projectId, input: iconPreviewSchema }, annotations: annotations(true) }, ({ projectId, input }) => guarded(async () => text(await engine.appIcons.preview(projectId, input))));
  server.registerTool('icon_apply', { description: 'Apply the reviewed app.json proposal only with user confirmation and matching config, media and proposal revisions. Preserves unrelated fields. Requires separate native build/device verification.', inputSchema: { projectId, input: iconApplySchema }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.appIcons.apply(projectId, input))));
  server.registerTool('media_list', { description: 'Read the project creative brief, asset metadata, revisions, approved local paths and optional image capability. Images are separate resources.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text({ ...await engine.assets.list(projectId), ...await engine.mediaJobs.list(projectId) })));
  server.registerTool('media_read', { description: 'Read one project-scoped immutable PNG for visual review. Returns metadata, image and resource URI.', inputSchema: { projectId, assetId: z.uuid() }, annotations: annotations(true) }, ({ projectId, assetId }) => guarded(async () => {
    const { asset, bytes } = await engine.assets.read(projectId, assetId);
    return { ...text({ asset, uri: `builder://projects/${projectId}/media/${assetId}` }), content: [{ type: 'image', data: bytes.toString('base64'), mimeType: 'image/png' }, { type: 'text', text: JSON.stringify(asset) }] };
  }));
  server.registerTool('media_import', { description: 'Import bounded base64 PNG/JPEG/WebP bytes into immutable local assets. Use Studio binary upload for large files. No URLs, no execution, no provider requests.', inputSchema: { projectId, input: importBase64Schema }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.assets.import(projectId, input.metadata, Buffer.from(input.data, 'base64')))));
  server.registerTool('media_brief', { description: 'Save the revision-checked creative brief. Reference IDs must be approved assets in this project.', inputSchema: { projectId, input: briefUpdateSchema }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.assets.brief(projectId, input.expectedRevision, input.brief))));
  server.registerTool('media_approve', { description: 'Mark a reviewed local candidate approved. Does not authorize spending. Ask the user to choose after visual review.', inputSchema: { projectId, input: approveAssetSchema }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.assets.approve(projectId, input.assetId, input.expectedRevision))));
  server.registerTool('media_transform', { description: 'Create an immutable crop/resize child with explicit fit, focal point and background. Preserves the original; no provider call.', inputSchema: { projectId, input: transformSchema }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(await engine.assets.transform(projectId, input))));
  server.registerTool('media_request', { description: 'Stage OpenAI still-image generation/editing. Select model=gpt-6-astra for Astra directing GPT Image (count=1; text and image charges) or omit model for direct GPT Image (count=1–2). NO provider call until the user reviews model, exact prompt, references and settings and approves in Studio. Use a stable requestId; never retry automatically.', inputSchema: { projectId, input: jobRequestSchema }, annotations: { ...annotations(false), openWorldHint: true } }, ({ projectId, input }) => guarded(async () => text(await engine.mediaJobs.request(projectId, input))));
  server.registerTool('media_job', { description: 'Read a project-scoped image job and next-action guidance. Poll queued/running jobs; do not resubmit.', inputSchema: { projectId, jobId: z.uuid() }, annotations: annotations(true) }, ({ projectId, jobId }) => guarded(async () => text(await engine.mediaJobs.get(projectId, jobId))));
  const kitMetadata = (kit: LaunchKit) => ({ ...kit, resources: kit.files.map(file => ({ fileId: file.id, mimeType: file.mediaType, uri: `builder://projects/${kit.manifest.project.id}/launch-kits/${kit.manifest.id}/files/${file.id}` })) });
  server.registerTool('launch_kit_create', { description: 'Durably copy 1–10 reviewed existing web captures, optional approved opaque 1024px icon and authored drafts into an immutable local Launch Kit. Requires explicit user confirmation of selected contents. No provider calls, app-source changes, store certification or publication. React Native Web captures are fresh-context route renders, not visible-phone state or native App Store screenshots. Expired captures must be deliberately recaptured and reviewed.', inputSchema: { projectId, input: launchKitCreateSchema }, annotations: annotations(false) }, ({ projectId, input }) => guarded(async () => text(kitMetadata(await engine.launchKits.create(projectId, input)))));
  server.registerTool('launch_kit_list', { description: 'List persistent project-scoped local Launch Kits and scoped file resources. Metadata only; no binary bundles. Web captures are not native App Store screenshots.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => guarded(async () => text({ kits: (await engine.launchKits.list(projectId)).map(kitMetadata) })));
  server.registerTool('launch_kit_read', { description: 'Read and verify a persistent local kit manifest, hashes and scoped file resources. Does not collect app source or recapture expired originals. Web captures are not native screenshots.', inputSchema: { projectId, bundleId: z.uuid() }, annotations: annotations(true) }, ({ projectId, bundleId }) => guarded(async () => text(kitMetadata(await engine.launchKits.read(projectId, bundleId)))));
  server.registerTool('launch_kit_remove', { description: 'Permanently delete only the named validated project-owned local Launch Kit with explicit user confirmation. Does not remove original captures, assets or app source.', inputSchema: { projectId, input: launchKitRemoveSchema }, annotations: annotations(false, true) }, ({ projectId, input }) => guarded(async () => text(await engine.launchKits.remove(projectId, input))));
  server.registerResource('launch-kit-file', new ResourceTemplate('builder://projects/{projectId}/launch-kits/{bundleId}/files/{fileId}', { list: undefined }), { description: 'One allowlisted immutable Launch Kit file, validated and project-scoped; no arbitrary paths' }, async (uri, variables) => {
    const { file, bytes } = await engine.launchKits.readFile(projectId.parse(variables.projectId), z.uuid().parse(variables.bundleId), kitFileIdSchema.parse(variables.fileId));
    return { contents: [file.mediaType === 'image/png' ? { uri: uri.href, mimeType: file.mediaType, blob: bytes.toString('base64') } : { uri: uri.href, mimeType: file.mediaType, text: bytes.toString('utf8') }] };
  });
  server.registerTool('media_cancel', { description: 'Cancel local waiting/running work. Cannot guarantee provider-side cancellation or a refund. Never automatically retry.', inputSchema: { projectId, jobId: z.uuid() }, annotations: annotations(false, true) }, ({ projectId, jobId }) => guarded(async () => text(await engine.mediaJobs.cancel(projectId, jobId))));
  server.registerResource('media', new ResourceTemplate('builder://projects/{projectId}/media/{assetId}', { list: undefined }), { mimeType: 'image/png' }, async (uri, variables) => {
    const { bytes } = await engine.assets.read(projectId.parse(variables.projectId), z.uuid().parse(variables.assetId));
    return { contents: [{ uri: uri.href, blob: bytes.toString('base64'), mimeType: 'image/png' }] };
  });
  server.registerResource('design-guide', 'builder://guide', { mimeType: 'application/json', description: 'Recipes, presets, design guidance, and step-by-step phone, native-build and Supabase environment setup for users and agents' }, async uri => ({ contents: [{ uri: uri.href, text: JSON.stringify({ recipes, presets, guidance, testingGuide, nativeBuildGuide }), mimeType: 'application/json' }] }));
  server.registerResource('board-capture', new ResourceTemplate('builder://projects/{projectId}/board-captures/{artifactId}', { list: undefined }), { mimeType: 'image/png' }, async (uri, variables) => {
    const png = await engine.boardCaptures.get(projectId.parse(variables.projectId), z.uuid().parse(variables.artifactId));
    return { contents: [{ uri: uri.href, blob: png.toString('base64'), mimeType: 'image/png' }] };
  });
  server.registerResource('projects', 'builder://projects', { mimeType: 'application/json', description: 'Registered project IDs and current runtime status' }, async uri => ({ contents: [{ uri: uri.href, text: JSON.stringify(await Promise.all((await engine.projects.list()).map(async p => ({ ...p, preview: engine.previews.status(p.id) })))), mimeType: 'application/json' }] }));
  server.registerResource('capture', new ResourceTemplate('builder://projects/{projectId}/captures/{artifactId}', { list: undefined }), { mimeType: 'image/png' }, async (uri, variables) => {
    const id = projectId.parse(variables.projectId); await engine.projects.get(id);
    const artifact = engine.captures.get(id, z.uuid().parse(variables.artifactId));
    return { contents: [{ uri: uri.href, blob: artifact.png.toString('base64'), mimeType: 'image/png' }] };
  });
  server.registerPrompt('build-mobile-app', { description: 'A brief → screens → build → capture → refine loop', argsSchema: { brief: z.string().min(1).max(4000) } }, ({ brief }) => ({ messages: [{ role: 'user', content: { type: 'text', text: `${brief}\n\n${guidance}\nUse project_create, project_inspect and revision-checked edits. Start a preview only with operator trust. Inspect every changed screen via preview_capture when vision is supported; otherwise ask for human review. End with diagnostics and independent run instructions.` } }] }));
}
