import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { Engine } from '../../core/src/engine.js';
import { backendCatalogInput, backendEnvironmentInput, backendPlanInput, backendRecoverySchema, backendSubmitSchema } from '../../core/src/backend-contracts.js';
import { environmentName, publicError } from '../../platform/src/contracts.js';
import { recipeUpgradeApplySchema } from '../../core/src/recipe-upgrades.js';
import { BuilderError } from '../../core/src/contracts.js';
import { functionEnvironmentDeclare, setupInput, validationInput, type ConfigurationPlan } from '../../platform/src/configuration.js';
import { hash } from '../../platform/src/crypto.js';
const projectId = z.uuid(), revision = z.string().regex(/^[a-f0-9]{64}$/).nullable();
const annotations = (readOnlyHint: boolean) => ({ readOnlyHint, destructiveHint: !readOnlyHint, idempotentHint: readOnlyHint, openWorldHint: true });
function configurationReview(plan: ConfigurationPlan) {
  const text = (value: unknown): unknown => typeof value === 'string' && value.length > 1000 ? { preview: value.slice(0, 1000), publicContentHash: hash(value), fullReview: 'Studio Backend' } : Array.isArray(value) ? value.map(text) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, text(item)])) : value;
  return { ...plan, preparedPlanHash: hash(plan), sources: plan.sources.map(({ path, revision }) => ({ path, revision })), steps: text(plan.steps), fullReview: 'Review the exact immutable source and complete changes in Studio Backend. Stage with preparedPlanHash; this bounded summary is not an executable plan.' };
}
function boundedOperation(value: unknown): unknown {
  if (!value || typeof value !== 'object') return value;
  const op = value as { plan?: ConfigurationPlan; operations?: unknown[] };
  if (op.plan?.version === 2) return { ...op, plan: configurationReview(op.plan) };
  if (Array.isArray(op.operations)) return { ...op, operations: op.operations.slice(0, 20).map(item => { const operation = item as { id: string; kind: string; state: string; environment: string; planHash: string; error: unknown }; return { id: operation.id, kind: operation.kind, state: operation.state, environment: operation.environment, planHash: operation.planHash, error: operation.error }; }), operationsTruncated: op.operations.length > 20 };
  return value;
}
async function actionResult(fn: () => Promise<unknown>, local = false) {
  try { const data = boundedOperation(await fn()); const object = data && typeof data === 'object' ? data as Record<string, unknown> : { result: data }; return { content: [{ type: 'text' as const, text: JSON.stringify(object) }], structuredContent: object }; }
  catch (error) { const object = { error: local && error instanceof BuilderError ? { code: error.code, message: error.message } : publicError(error) }; return { isError: true, content: [{ type: 'text' as const, text: JSON.stringify(object) }], structuredContent: object }; }
}
export function registerBackendTools(server: McpServer, engine: Engine) {
  const result = (fn: () => Promise<unknown>, local = false) => actionResult(async () => { const value = await fn(); await engine.projects.flushState(); return value; }, local);
  server.registerTool('backend_environment_inspect', { description: 'Read Edge Function environment variable names, private-input availability and sourceRevision. Values are never returned. Variables are shared by every Edge Function in the selected Supabase project. Read builder://guide for the user and agent setup steps.', inputSchema: { projectId, environment: environmentName.default('development') }, annotations: annotations(true) }, ({ projectId, environment }) => result(() => engine.backends.configuration.functionEnvironment(projectId, environment)));
  server.registerTool('backend_environment_declare', { description: 'Add one public variable name and opaque private-input requirement to backend/configuration.json with sourceRevision protection. Supply expectedSourceRevision from backend_environment_inspect. Never accepts a secret value. Direct the user to Backend Environment variables to supply it privately, then backend_plan action function_environment and backend_apply stage changes for human approval.', inputSchema: { projectId, input: functionEnvironmentDeclare }, annotations: { ...annotations(false), openWorldHint: false } }, ({ projectId, input }) => result(() => engine.backends.configuration.declareFunctionEnvironment(projectId, input)));
  server.registerTool('backend_recipe_preview', { description: 'Review the additive, versioned app-services source example: email templates, private uploads and an authenticated function. Preserves existing files and navigation; conflicts require a manual merge. No dependency or provider changes.', inputSchema: { projectId }, annotations: { ...annotations(true), openWorldHint: false } }, ({ projectId }) => result(() => engine.serviceRecipe.preview(projectId), true));
  server.registerTool('backend_recipe_apply', { description: 'Apply the exact reviewed additive services recipe after human confirmation, with proposedRevision from backend_recipe_preview. Stops preview, preserves edits and never modifies provider resources. confirmed must reflect a person’s approval.', inputSchema: { projectId, proposedRevision: z.string().regex(/^[a-f0-9]{64}$/), confirmed: z.literal(true) }, annotations: { ...annotations(false), openWorldHint: false } }, ({ projectId, ...input }) => result(() => engine.serviceRecipe.apply(projectId, input), true));
  server.registerTool('recipe_upgrade_preview', { description: 'Review the versioned Supabase recipe upgrade for a legacy generated app. Returns exact file, manifest and lockfile changes, conflicts, or interrupted-upgrade recovery. Read-only; preserves existing app source. No Supabase account is needed.', inputSchema: { projectId }, annotations: { ...annotations(true), openWorldHint: false } }, ({ projectId }) => result(() => engine.recipeUpgrades.preview(projectId), true));
  server.registerTool('recipe_upgrade_apply', { description: 'Apply or recover the exact reviewed local recipe proposal with explicit confirmation and matching proposedRevision. Review all changes first; never infer human approval from model output. Stops the preview and preserves conflicting edits. Does not provision a backend or execute SQL.', inputSchema: recipeUpgradeApplySchema, annotations: { ...annotations(false), openWorldHint: false } }, input => result(() => engine.recipeUpgrades.apply(input.projectId, input), true));
  server.registerTool('backend_inspect', { description: 'Read this app’s Supabase bindings and durable backend operations. Does not expose management credentials or query app user data.', inputSchema: { projectId }, annotations: annotations(true) }, ({ projectId }) => result(() => engine.backends.inspect(projectId)));
  server.registerTool('backend_catalog', { description: 'Discover Supabase organizations and projects for this app’s setup. Bounded pages disclose totals and truncation; pass nextOffset as offset and the returned revision as expectedRevision to continue. Reload from page zero on conflict. Names can be ambiguous: require an explicit organization and project reference; never choose the first result automatically.', inputSchema: { projectId, input: backendCatalogInput.optional() }, annotations: annotations(true) }, ({ projectId, input }, extra) => result(() => engine.backends.catalog(projectId, input, extra.signal)));
  server.registerTool('backend_capabilities', { description: 'Read this app’s configuration prerequisites and observe Supabase metadata-read permissions. No mutating probes, user data, keys, or Auth configuration values are returned. A successful read does not imply write permission; unknown scopes remain unknown. Defaults to the active environment.', inputSchema: { projectId, environment: environmentName.optional() }, annotations: annotations(true) }, ({ projectId, environment }, extra) => result(() => engine.backends.capabilities(projectId, environment, extra.signal)));
  server.registerTool('backend_select_environment', { description: 'Select an already linked environment for this app’s previews, using environmentRevision from backend_inspect as expectedRevision. Stops the existing preview and makes captures from other configurations stale. The app must still be selected in Studio. Does not start a preview or mutate Supabase.', inputSchema: { projectId, input: backendEnvironmentInput }, annotations: { ...annotations(false), openWorldHint: false } }, ({ projectId, input }, extra) => result(() => engine.selectBackendEnvironment(projectId, input, extra.signal), true));
  server.registerTool('backend_plan', { description: 'Prepare a Supabase link/create/migration or configure proposal. Configure reads backend/configuration.json, scoped templates, and vendored function source. Returns a bounded review and preparedPlanHash for backend_apply; the complete immutable review is shown in Studio. Read prerequisites and obtain private inputs in Studio, never chat. No external mutation.', inputSchema: { projectId, input: backendPlanInput }, annotations: annotations(true) }, ({ projectId, input }, extra) => result(async () => {
    if (input.action !== 'configure' && input.action !== 'function_environment' && input.action !== 'verify') return engine.backends.plan(projectId, input, extra.signal);
    const plan = input.action === 'verify' ? await engine.backends.configuration.planVerification(projectId, input, extra.signal) : await engine.backends.plan(projectId, input, extra.signal);
    return configurationReview(plan);
  }));
  server.registerTool('backend_validate', { description: 'Static source and read-only remote precondition checks. Returns timestamped pass/fail/blocked/not_run evidence. Never sends email, runs SQL/functions, invokes test code, or writes test data. planHash is the preparedPlanHash from backend_plan.', inputSchema: { projectId, input: validationInput }, annotations: annotations(true) }, ({ projectId, input }, extra) => result(() => engine.backends.configuration.validate(projectId, input, extra.signal)));
  server.registerTool('backend_requirements', { description: 'Read or declare named private-input requirements from backend/configuration.json for this environment. Returns availability and opaque revisions only. Ask the person to enter values in Studio Backend; never solicit secrets in chat or tool arguments.', inputSchema: { projectId, environment: environmentName.default('development') }, annotations: annotations(true) }, ({ projectId, environment }) => result(() => engine.backends.configuration.requirements(projectId, environment)));
  server.registerTool('backend_setup', { description: 'Start or resume a durable email/complete setup journey. Track source, explicit backend choice, secure inputs, reviews, recovery, validation, and exports. It never approves changes or allocates resources. Each dependent plan is prepared only after the actual binding exists. Use a stable requestId.', inputSchema: { projectId, input: setupInput }, annotations: { ...annotations(false), openWorldHint: false } }, ({ projectId, input }) => result(() => engine.backends.configuration.setup(projectId, input)));
  server.registerTool('backend_apply', { description: 'Stage the exact backend plan as a durable operation. Does not execute it until an authenticated person approves the matching plan in Studio Backend. Use a stable requestId and poll backend_operation; never treat the model as an approver.', inputSchema: { projectId, input: backendSubmitSchema }, annotations: annotations(false) }, ({ projectId, input }, extra) => result(() => engine.backends.submit(projectId, input, extra.signal)));
  server.registerTool('backend_operation', { description: 'Read a project-scoped backend operation, plan, outcome and recovery state. Never resubmit an operation with an unknown external outcome.', inputSchema: { projectId, operationId: z.uuid() }, annotations: annotations(true) }, ({ projectId, operationId }) => result(() => engine.backends.operation(projectId, operationId)));
  server.registerTool('backend_cancel', { description: 'Stop further execution of a backend operation. An in-flight provider request may have completed; cancellation does not delete resources or undo migrations.', inputSchema: { projectId, operationId: z.uuid() }, annotations: annotations(false) }, ({ projectId, operationId }) => result(() => engine.backends.cancel(projectId, operationId)));
  server.registerTool('backend_reconcile', { description: 'Check an interrupted operation against provider evidence and finish local bookkeeping when its exact outcome is known. Use the planHash and fence from backend_operation. Never repeats project creation or SQL; missing or conflicting evidence keeps the environment paused.', inputSchema: { projectId, input: backendRecoverySchema }, annotations: annotations(false) }, ({ projectId, input }) => result(() => engine.backends.reconcile(projectId, input)));
  server.registerTool('backend_generate_types', { description: 'Read the selected backend schema and write src/backend/database.types.ts with the supplied current file revision. Does not read application rows.', inputSchema: { projectId, environment: environmentName.default('development'), expectedRevision: revision }, annotations: annotations(false) }, ({ projectId, environment, expectedRevision }, extra) => result(() => engine.backends.generateTypes(projectId, environment, expectedRevision, extra.signal)));
  server.registerTool('backend_export_config', { description: 'Write portable public backend/connection.json for this environment, with revision protection. Contains only the app URL and publishable key; no Dunara runtime or management credentials.', inputSchema: { projectId, environment: environmentName.default('development'), expectedRevision: revision }, annotations: annotations(false) }, ({ projectId, environment, expectedRevision }) => result(() => engine.backends.exportConfiguration(projectId, environment, expectedRevision)));
}
