import { openProjectRoutes } from './preview-actions.js';
import { closeMediaDrawer, openIconSettings } from './media-workspace-helpers.js';
import { selectProject } from './project-picker.js';
import { test, expect } from '@playwright/test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { z } from 'zod';
import { createMcpServer } from '../../packages/mcp/src/server.js';
import { manifestSchema } from '../../packages/core/src/media-contracts.js';
import { revisionSchema } from '../../packages/core/src/contracts.js';
import { ASTRA_MODEL, IMAGE_MODEL, mediaModelLabel, type JobRequest } from '../../packages/core/src/media-job-contracts.js';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { Engine } from '../../packages/core/src/engine.js';
import { Projects } from '../../packages/core/src/projects.js';
import { startStudio } from '../../packages/cli/src/studio-server.js';

test.use({ trace: 'off' });
let dir: string, engine: Engine, studio: Awaited<ReturnType<typeof startStudio>>, bytes: Buffer, projectId: string;
test.beforeEach(async () => {
  test.skip(!!process.env.VISUAL, 'Visual suite only');
  dir = await mkdtemp(path.join(os.tmpdir(), 'studio-assets-'));
  engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false);
  projectId = (await engine.projects.create({ name: 'Asset Review', slug: 'asset-review' })).id;
  studio = await startStudio(engine, path.resolve('dist/studio'));
  bytes = await sharp({ create: { width: 100, height: 80, channels: 3, background: '#567b68' } }).png().toBuffer();
});
test.afterEach(async () => { if (process.env.VISUAL) return; await studio.close(); await engine.close(); await rm(dir, { recursive: true, force: true }); });

test('shared creative loop integrates a local image in real Expo and persists icons across restart', async ({ page }) => {
  await studio.close(); await engine.close();
  engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), true);
  studio = await startStudio(engine, path.resolve('dist/studio'));
  const server = createMcpServer(engine), client = new Client({ name: 'creative-loop', version: '1' });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const librarySchema = manifestSchema.extend({ revision: revisionSchema.nullable() }).passthrough();
  const call = async (name: string, args: Record<string, unknown> = {}) => {
    const result = await client.callTool({ name, arguments: { projectId, ...args } });
    expect(result.isError, JSON.stringify(result.structuredContent)).not.toBe(true);
    return result;
  };
  try {
    await server.connect(serverTransport); await client.connect(clientTransport);
    await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
    await closeMediaDrawer(page); await page.getByRole('button', { name: 'Art direction', exact: true }).click();
    await page.getByRole('textbox', { name: 'Mood', exact: true }).fill('Botanical exploration');
    await page.getByRole('button', { name: 'Save brief' }).click();
    await expect(page.getByRole('button', { name: 'Save brief' })).toBeDisabled();
    await closeMediaDrawer(page); await page.getByRole('button', { name: 'Import', exact: true }).click();
    await page.getByLabel('Image file').setInputFiles({ name: 'Creative-original.png', mimeType: 'image/png', buffer: bytes });
    await page.getByRole('button', { name: 'Import candidate', exact: true }).click();
    await closeMediaDrawer(page); await page.getByRole('button', { name: 'Creative-original.png', exact: true }).click();
    let library = librarySchema.parse((await call('media_list')).structuredContent);
    expect(library.brief.mood).toBe('Botanical exploration');
    const original = library.assets[0]!;
    const resource = await client.readResource({ uri: `builder://projects/${projectId}/media/${original.id}` });
    const originalBytes = z.object({ blob: z.string() }).parse(resource.contents[0]).blob;
    library = librarySchema.parse((await call('media_transform', { input: { assetId: original.id, expectedRevision: library.revision, width: 64, height: 64, fit: 'cover' } })).structuredContent);
    const child = library.assets[1]!;
    await page.getByRole('button', { name: child.label, exact: true }).click();
    await expect(page.locator('.media-comparison img')).toHaveCount(2);
    await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Approved for integration' })).toBeDisabled();
    library = librarySchema.parse((await call('media_list')).structuredContent);
    expect(library.assets[1]).toMatchObject({ status: 'approved', parentId: original.id });
    const source = `import { Image, View, Text } from 'react-native';\nexport default function Creative() { return <View style={{ flex: 1, backgroundColor: '#ffffff', padding: 24 }}><Text>Approved local artwork</Text><Image accessibilityLabel="Approved botanical illustration" source={require('../${child.path}')} style={{ width: 256, height: 256 }} /></View>; }\n`;
    await call('project_write_files', { writes: [{ path: 'app/creative.tsx', expectedRevision: null, content: source }] });
    const inspected = z.object({ files: z.array(z.object({ content: z.string(), revision: revisionSchema })) }).parse((await call('project_inspect', { paths: ['app/creative.tsx'] })).structuredContent);
    await call('project_write_files', { writes: [{ path: 'app/creative.tsx', expectedRevision: inspected.files[0]!.revision, content: source.replace('Approved local artwork', 'Creative loop verified') }] });
    await closeMediaDrawer(page); await page.getByRole('button', { name: 'Preview', exact: true }).click();
    await page.getByRole('button', { name: 'Start preview' }).click();
    await expect(page.getByRole('button', { name: 'Stop preview' })).toBeVisible({ timeout: 180_000 });
    await openProjectRoutes(page);
    await page.getByLabel('Agent-added screen').fill('/creative'); await page.getByLabel('Agent-added screen').press('Enter');
    const frame = page.frameLocator('iframe');
    await expect(frame.getByText('Creative loop verified')).toBeVisible({ timeout: 60_000 });
    const image = frame.getByRole('img', { name: 'Approved botanical illustration', exact: true });
    await expect(image).toBeVisible();
    await expect(image).toHaveJSProperty('naturalWidth', 64);
    const capture = await call('preview_capture', { route: '/creative', viewport: 'compact' });
    const contents = z.array(z.object({ type: z.string(), data: z.string().optional() })).parse(capture.content);
    const imageContent = z.object({ type: z.literal('image'), data: z.string() }).parse(contents.find(item => item.type === 'image'));
    const pixels = await sharp(Buffer.from(imageContent.data, 'base64')).removeAlpha().raw().toBuffer();
    let matching = 0;
    for (let i = 0; i < pixels.length; i += 3) if (pixels[i] === 86 && pixels[i + 1] === 123 && pixels[i + 2] === 104) matching++;
    expect(matching).toBeGreaterThan(60_000);
    await page.getByRole('button', { name: 'Activity', exact: true }).click();
    await page.getByRole('button', { name: /^Captures/ }).click();
    const thumbnail = page.getByRole('button', { name: 'Open capture of /creative · compact', exact: true });
    await expect(thumbnail.locator('img')).toHaveJSProperty('naturalWidth', 375);
    for (const viewport of [{ width: 1280, height: 800 }, { width: 375, height: 812 }, { width: 430, height: 932 }]) {
      await page.setViewportSize(viewport);
      await expect(thumbnail).toBeInViewport();
      await expect(page.getByRole('button', { name: 'Prepare Launch Kit', exact: true })).toBeInViewport();
      await page.screenshot({ path: test.info().outputPath(`capture-gallery-${viewport.width}.png`) });
    }
    await thumbnail.click();
    await expect(page.getByRole('dialog').getByRole('img')).toHaveJSProperty('naturalWidth', 375);
    await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
    await page.getByRole('combobox', { name: 'Capture size' }).click();
    await page.getByRole('option', { name: 'Large', exact: true }).click();
    await expect(page.getByText('No matching captures', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Clear filters', exact: true }).click();
    await expect(thumbnail).toBeVisible();
    await page.setViewportSize({ width: 1440, height: 1100 });
    library = librarySchema.parse((await call('icon_prepare', { input: { assetId: child.id, expectedRevision: library.revision, kind: 'master', fit: 'contain', background: '#ffffff' } })).structuredContent);
    const master = library.assets.at(-1)!;
    library = librarySchema.parse((await call('media_approve', { input: { assetId: master.id, expectedRevision: library.revision } })).structuredContent);
    const selection = { masterId: master.id, background: '#ffffff' };
    const diff = z.object({ before: z.string(), after: z.string(), expectedConfigRevision: revisionSchema, expectedMediaRevision: revisionSchema, proposedRevision: revisionSchema }).parse((await call('icon_preview', { input: selection })).structuredContent);
    expect(JSON.parse(diff.after).expo.icon).toBe(`./${master.path}`);
    await call('icon_apply', { input: { ...selection, expectedConfigRevision: diff.expectedConfigRevision, expectedMediaRevision: diff.expectedMediaRevision, proposedRevision: diff.proposedRevision, confirmed: true } });
    const project = await engine.projects.get(projectId);
    expect(await readFile(path.join(project.root, 'app.json'), 'utf8')).toBe(diff.after);
    expect(await sharp((await engine.assets.read(projectId, master.id)).bytes).metadata()).toMatchObject({ width: 1024, height: 1024, hasAlpha: false });
    expect((await client.readResource({ uri: `builder://projects/${projectId}/media/${original.id}` })).contents[0]).toEqual(resource.contents[0]);
    expect(originalBytes).toBeTruthy();
    expect(await readFile(path.join(project.root, 'package.json'), 'utf8')).not.toMatch(/openai|sharp|mobile-app-builder/);
    await call('preview_stop');
    await studio.close(); await engine.close();
    engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false);
    studio = await startStudio(engine, path.resolve('dist/studio'));
    expect(await engine.assets.list(projectId)).toMatchObject({ revision: library.revision, brief: { mood: 'Botanical exploration' } });
    expect((await engine.assets.read(projectId, child.id)).asset.status).toBe('approved');
    expect((await engine.appIcons.preview(projectId, selection)).before).toBe(diff.after);
    await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
    await page.getByRole('button', { name: child.label, exact: true }).click();
    await expect(page.locator('.media-comparison img').nth(1)).toHaveJSProperty('naturalWidth', 64);
    await expect(page.getByRole('button', { name: 'Approved for integration' })).toBeDisabled();
  } finally { await client.close(); await server.close(); }
});

test('offline brief, import, rendered comparison, transforms and approval persist', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(page.getByText('Asset library ready · Image generation needs setup')).toBeVisible();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Stage request for review' })).toBeDisabled();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Art direction', exact: true }).click();
    await page.getByRole('textbox', { name: 'Mood', exact: true }).fill('Botanical exploration'); await page.getByRole('button', { name: 'Save brief' }).click();
  await expect.poll(async () => (await engine.assets.list(projectId)).brief.mood).toBe('Botanical exploration');
  await expect(page.getByRole('button', { name: 'Save brief' })).toBeDisabled();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Import', exact: true }).click();
    await page.getByLabel('Image file').setInputFiles({ name: 'Original.png', mimeType: 'image/png', buffer: bytes });
  await page.getByLabel('Provenance / rights note').fill('Original test fixture');
  await page.getByRole('button', { name: 'Import candidate', exact: true }).click();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Original.png', exact: true }).click();
  await expect(page.locator('.media-comparison img')).toHaveJSProperty('naturalWidth', 100);
  await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Approved for integration' })).toBeDisabled();
  await page.getByText('Crop and resize a new version', { exact: true }).filter({ hasNot: page.locator('*') }).first().click();
  await page.getByLabel('Width', { exact: true }).fill('64'); await page.getByLabel('Height', { exact: true }).fill('64');
  await page.getByRole('button', { name: 'Create transformed candidate' }).click();
  await expect.poll(async () => (await engine.assets.list(projectId)).assets.length).toBe(2);
  const library = await engine.assets.list(projectId), child = library.assets[1]!;
  await page.locator('.asset-tile').nth(1).getByRole('button').click();
  await expect(page.locator('.media-comparison img')).toHaveCount(2);
  await expect(page.locator('.media-comparison img').nth(1)).toHaveJSProperty('naturalWidth', 64);
  expect(child.parentId).toBe(library.assets[0]!.id);
  await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
  await expect.poll(async () => (await engine.assets.list(projectId)).assets[1]!.status).toBe('approved');
  expect(errors).toEqual([]);
  await studio.close(); await engine.close();
  engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false);
  studio = await startStudio(engine, path.resolve('dist/studio'));
  expect((await engine.assets.list(projectId)).assets[1]).toMatchObject({ id: child.id, status: 'approved', parentId: child.parentId });
});

test('brief errors remain retryable and delayed project results cannot cross selections', async ({ page }) => {
  const other = await engine.projects.create({ name: 'Other Assets', slug: 'other-assets' });
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Art direction', exact: true }).click();
    await page.getByRole('textbox', { name: 'Mood', exact: true }).fill('Keep this draft');
  await page.route('**/media/brief', route => route.fulfill({ status: 400, json: { error: { message: 'Deliberate media failure' } } }));
  await page.getByRole('button', { name: 'Save brief' }).click();
  await expect(page.getByRole('alert')).toContainText('Deliberate media failure');
  await expect(page.getByRole('textbox', { name: 'Mood', exact: true })).toHaveValue('Keep this draft');
  await page.unroute('**/media/brief');
  await engine.assets.brief(projectId, null, { mood: 'External direction' });
  await expect(page.getByRole('button', { name: 'Review brief against latest revision' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Save brief' })).toBeDisabled();
  await page.getByRole('button', { name: 'Review brief against latest revision' }).click();
  let release!: () => void, received!: () => void;
  const held = new Promise<void>(resolve => { release = resolve; }), arrived = new Promise<void>(resolve => { received = resolve; });
  await page.route(`**/projects/${projectId}/media/brief`, async route => { received(); await held; await route.continue(); });
  await page.getByRole('button', { name: 'Save brief' }).click(); await arrived;
  await closeMediaDrawer(page); await selectProject(page, other.id);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Art direction', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Mood', exact: true })).toHaveValue(''); release();
  await expect.poll(async () => (await engine.assets.list(projectId)).brief.mood).toBe('Keep this draft');
  await expect(page.getByRole('textbox', { name: 'Mood', exact: true })).toHaveValue('');
});

test('art direction limits references to ten while allowing a replacement and successful save', async ({ page }) => {
  let library = await engine.assets.list(projectId);
  for (let index = 1; index <= 11; index++) {
    library = await engine.assets.import(projectId, { expectedRevision: library.revision, mediaType: 'image/png', label: `Direction ${index}` }, bytes);
    library = await engine.assets.approve(projectId, library.assets.at(-1)!.id, library.revision);
  }
  await page.goto(studio.launchUrl);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Art direction', exact: true }).click();
  const form = page.getByRole('region', { name: 'Art direction form' });
  for (let index = 1; index <= 10; index++) await form.getByRole('checkbox', { name: `Direction ${index}`, exact: true }).check();
  const last = form.getByRole('checkbox', { name: 'Direction 11', exact: true });
  await expect(last).toBeDisabled();
  await expect(form).toContainText('10 of 10 selected');
  await form.getByRole('checkbox', { name: 'Direction 1', exact: true }).uncheck();
  await expect(last).toBeEnabled();
  await last.check();
  await form.getByRole('button', { name: 'Save brief' }).click();
  await expect(form.getByRole('button', { name: 'Save brief' })).toBeDisabled();
  await expect.poll(async () => (await engine.assets.list(projectId)).brief.referenceIds).toEqual(library.assets.slice(1).map(asset => asset.id));
});

test('paid request disclosure requires explicit approval and edit retains its original', async ({ page }) => {
  await studio.close(); await engine.close(); let calls = 0; const requests: JobRequest[] = [];
  engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false, false, { async run(request) { calls++; requests.push(request); return [bytes]; } });
  studio = await startStudio(engine, path.resolve('dist/studio'));
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await page.locator('.creative-options > summary').click();
  await expect(page.getByRole('combobox', { name: 'Generation model' })).toContainText('Astra + GPT Image');
  await page.getByRole('combobox', { name: 'Candidates' }).click();
  await expect(page.getByRole('option')).toHaveCount(1);
  await page.getByRole('option', { name: '1', exact: true }).click();
  await page.getByRole('combobox', { name: 'Generation model' }).click();
  await page.getByRole('option', { name: 'GPT Image direct', exact: true }).click();
  await page.getByRole('combobox', { name: 'Candidates' }).click();
  await page.getByRole('option', { name: '2', exact: true }).click();
  await page.getByRole('combobox', { name: 'Generation model' }).click();
  await page.getByRole('option', { name: 'Astra + GPT Image', exact: true }).click();
  await expect(page.getByRole('combobox', { name: 'Candidates' })).toContainText('1');
  await page.getByLabel('Image prompt').fill('An original botanical explorer');
  await page.getByRole('button', { name: 'Stage request for review' }).click();
  await expect(page.getByText('New illustration · Ready to generate')).toBeVisible();
  expect(calls).toBe(0);
  await expect(page.getByRole('button', { name: 'Approve paid request' })).toBeDisabled();
  await expect(page.locator('.media-prompt')).toContainText('An original botanical explorer');
  await expect(page.locator('.media-prompt')).toContainText('App art direction:');
  await expect(page.locator('.media-job')).toContainText(mediaModelLabel(ASTRA_MODEL));
  await page.getByText('Generation & billing details', { exact: true }).click();
  await expect(page.locator('.media-job')).toContainText('Text and image charges apply');
  await page.getByRole('checkbox', { name: /I authorize this exact paid request and disclosure/ }).check();
  await page.getByRole('button', { name: 'Approve paid request' }).click();
  await expect(page.getByText('New illustration · Ready to review')).toBeVisible(); expect(calls).toBe(1);
  await page.locator('.media-job').getByRole('button', { name: /^Review New illustration/ }).click();
  await expect(page.getByRole('heading', { name: 'Review candidate', exact: true })).toBeFocused();
  await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Approved for integration' })).toBeDisabled();
  const original = (await engine.assets.list(projectId)).assets[0]!;
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await page.locator('.creative-options > summary').click();
  await page.getByRole('combobox', { name: 'Operation', exact: true }).click();
  await page.getByRole('option', { name: 'Edit approved image', exact: true }).click();
  await page.getByLabel('Request label').fill('Explorer edit');
  await page.locator('form').filter({ has: page.getByRole('textbox', { name: 'Image prompt' }) }).getByRole('checkbox', { name: original.label }).check();
  await page.getByRole('button', { name: 'Stage request for review' }).click();
  const job = page.locator('.media-job').filter({ hasText: 'Explorer edit' });
  await expect(job.locator('img')).toHaveJSProperty('naturalWidth', 100);
  expect(calls).toBe(1);
  await job.getByRole('checkbox').check(); await job.getByRole('button', { name: 'Approve paid request' }).click();
  await expect(job.getByRole('heading', { level: 3 })).toHaveText('Explorer edit · Ready to review');
  expect((await engine.assets.list(projectId)).assets[1]).toMatchObject({ parentId: original.id, provenance: 'edited', status: 'candidate' });
  expect((await engine.assets.read(projectId, original.id)).asset.hash).toBe(original.hash); expect(calls).toBe(2);
  expect(requests.map(request => request.model)).toEqual([ASTRA_MODEL, ASTRA_MODEL]);
  expect((await engine.assets.list(projectId)).assets[1]?.model).toBe(mediaModelLabel(ASTRA_MODEL));
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Generate', exact: true }).click();
  await page.locator('.creative-options > summary').click();
  await page.getByRole('combobox', { name: 'Generation model' }).click();
  await page.getByRole('option', { name: 'GPT Image direct', exact: true }).click();
  await page.getByRole('combobox', { name: 'Operation', exact: true }).click();
  await page.getByRole('option', { name: 'Generate', exact: true }).click();
  await page.getByLabel('Request label').fill('Direct fallback');
  await page.getByRole('button', { name: 'Stage request for review' }).click();
  const direct = page.locator('.media-job').filter({ hasText: 'Direct fallback' });
  await expect(direct).toContainText(`OpenAI / ${IMAGE_MODEL}`);
  await expect(direct).not.toContainText('Text and image charges apply');
  expect(calls).toBe(2); await direct.getByRole('button', { name: 'Cancel local job' }).click();
  await expect(direct.getByRole('heading', { level: 3 })).toHaveText('Direct fallback · Cancelled');
});

test('asset controls fit mobile and 200 percent scaling and image failures are retryable', async ({ page }) => {
  const imported = await engine.assets.import(projectId, { expectedRevision: null, mediaType: 'image/png', label: 'Retry original' }, bytes);
  await page.addInitScript(() => { const original = URL.revokeObjectURL; let revoked = 0; URL.revokeObjectURL = url => { revoked++; original(url); }; Object.defineProperty(window, 'revokedBlobs', { get: () => revoked }); });
  await page.route('**/media/images/**', route => route.fulfill({ status: 400, json: { error: { message: 'Temporary' } } }));
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Retry image' })).toBeVisible();
  await page.unroute('**/media/images/**'); await page.getByRole('button', { name: 'Retry image' }).click();
  await expect(page.locator('.asset-tile img')).toHaveJSProperty('naturalWidth', 100);
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const small = await page.locator('.assets-workspace button:visible, .assets-workspace input:not([type=checkbox]):visible, .assets-workspace select:visible, .assets-workspace textarea:visible').evaluateAll(elements => elements.filter(el => { const box = el.getBoundingClientRect(); const minimum = matchMedia('(max-width: 760px), (pointer: coarse)').matches ? 44 : 36; return box.width < minimum || box.height < minimum; }).map(el => el.outerHTML));
    expect(small).toEqual([]);
  }
  await page.evaluate(() => { document.documentElement.style.zoom = '2'; });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Retry original', exact: true }).focus();
  await page.keyboard.press('Enter'); await expect(page.getByRole('heading', { name: 'Review candidate' })).toBeVisible();
  const other = await engine.projects.create({ name: 'Switch target', slug: 'switch-target' });
  await closeMediaDrawer(page); await selectProject(page, other.id);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(page.getByText('No assets yet.', { exact: false })).toBeVisible();
  expect(await page.evaluate(() => Reflect.get(window, 'revokedBlobs'))).toBeGreaterThan(0);
  expect(imported.assets).toHaveLength(1);
});

test('library-first forms preserve drafts, recover malformed imports, and copy approved integration context', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw Error('Clipboard denied'); } } }));
  await page.goto(studio.launchUrl);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Asset library' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Import an original' })).toBeHidden();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Import', exact: true }).click();
  await page.getByLabel('Image file').setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('not an image') });
  await page.getByLabel('Provenance / rights note').fill('My rights note');
  await page.getByRole('button', { name: 'Import candidate', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  expect((await engine.assets.list(projectId)).assets).toHaveLength(0);
  await page.getByRole('button', { name: 'Close import' }).click();
  await expect(page.getByRole('button', { name: 'Import', exact: true })).toBeFocused();
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(page.getByLabel('Provenance / rights note')).toHaveValue('My rights note');
  await page.getByLabel('Image file').setInputFiles({ name: 'Approved artwork.png', mimeType: 'image/png', buffer: bytes });
  await page.getByRole('button', { name: 'Import candidate', exact: true }).click();
  await page.getByRole('button', { name: 'Close import' }).click();
  await page.getByRole('button', { name: 'Approved artwork.png', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Review candidate' })).toBeFocused();
  await expect(page.getByRole('button', { name: 'Copy integration context' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
  await page.getByRole('button', { name: 'Copy integration context' }).click();
  const context = page.getByRole('textbox', { name: 'Integration context (selectable fallback)' });
  await expect(context).toBeFocused();
  await expect(page.getByText('Clipboard unavailable.', { exact: false })).toBeVisible();
  const asset = (await engine.assets.list(projectId)).assets[0]!;
  expect(JSON.parse(await context.inputValue())).toMatchObject({ projectId, assetId: asset.id, path: asset.path, status: 'approved' });
  expect(await context.evaluate((node: HTMLTextAreaElement) => node.selectionEnd - node.selectionStart)).toBe((await context.inputValue()).length);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text: string) => { Reflect.set(window, 'copiedAssetContext', text); } } }));
  await page.getByRole('button', { name: 'Copy integration context' }).click();
  await expect(page.getByText('Integration context copied.', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => Reflect.get(window, 'copiedAssetContext'))).toBe(await context.inputValue());
  const other = await engine.projects.create({ name: 'Empty isolation fixture', slug: 'empty-isolation-fixture' });
  await closeMediaDrawer(page); await selectProject(page, other.id);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'Integration context (selectable fallback)' })).toHaveCount(0);
  await closeMediaDrawer(page); await page.getByRole('button', { name: 'Import', exact: true }).click();
  await expect(page.getByLabel('Provenance / rights note')).toHaveValue('');
});

test('creative forms and selected review stay reachable at six widths and 200 percent zoom', async ({ page }) => {
  const library = await engine.assets.import(projectId, { expectedRevision: null, mediaType: 'image/png', label: 'An intentionally long candidate label for responsive local integration and careful review', rightsNote: 'Original offline test fixture' }, bytes);
  await engine.assets.approve(projectId, library.assets[0]!.id, library.revision);
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await page.getByRole('button', { name: library.assets[0]!.label, exact: true }).click();
  for (const width of [320, 375, 430, 768, 1280, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    for (const zoom of [1, 2]) {
      await page.evaluate(value => { document.documentElement.style.zoom = String(value); }, zoom);
      for (const form of ['Import', 'Art direction', 'Generate']) {
        await closeMediaDrawer(page); await page.getByRole('button', { name: form, exact: true }).click();
        const overflow = await page.evaluate(() => [...document.querySelectorAll('body *')].filter(el => { const box = el.getBoundingClientRect(); return box.width && box.right > innerWidth + 1; }).map(el => `${el.tagName}.${el.className}: ${Math.round(el.getBoundingClientRect().right)}`));
        expect(overflow, `${width}px / ${zoom} zoom / ${form}`).toEqual([]);
        const small = await page.locator('.assets-workspace button:visible, .assets-workspace input:not([type=checkbox]):visible, .assets-workspace textarea:visible').evaluateAll(elements => elements.filter(el => { const box = el.getBoundingClientRect(); const minimum = matchMedia('(max-width: 760px), (pointer: coarse)').matches ? 44 : 36; return box.width < minimum || box.height < minimum; }).map(el => el.outerHTML));
        expect(small).toEqual([]);
        await closeMediaDrawer(page);
      }
      const details = page.getByRole('button', { name: 'Details', exact: true });
      if (await details.isVisible()) await details.click();
      const copy = page.getByRole('button', { name: 'Copy integration context' });
      await copy.scrollIntoViewIfNeeded(); await expect(copy).toBeInViewport();
      await page.getByRole('combobox', { name: 'Compare with' }).click();
      await expect(page.getByRole('listbox')).toBeInViewport();
      await page.keyboard.press('Escape');
    }
  }
});

test('icon candidates render at small sizes and config application requires review and handles conflicts', async ({ page }) => {
  const imported = await engine.assets.import(projectId, { expectedRevision: null, mediaType: 'image/png', label: 'Icon source' }, bytes);
  await engine.assets.approve(projectId, imported.assets[0]!.id, imported.revision);
  const originalConfig = await engine.files.read(projectId, 'app.json');
  await page.goto(studio.launchUrl); await closeMediaDrawer(page); await page.getByRole('button', { name: 'Assets', exact: true }).click();
  await page.getByRole('button', { name: 'Icon source', exact: true }).click();
  await page.getByRole('button', { name: 'Use selected image in App Icons', exact: true }).click();
  await openIconSettings(page);
  await expect(page.getByRole('button', { name: 'Prepare adaptive foreground' })).toBeDisabled();
  await page.getByRole('button', { name: 'Prepare 1024px icon master' }).click();
  await expect.poll(async () => (await engine.assets.list(projectId)).assets.length).toBe(2);
  await openIconSettings(page); await page.getByRole('combobox', { name: 'Icon source', exact: true }).click();
  await page.getByRole('option', { name: `${(await engine.assets.list(projectId)).assets[1]!.label} · candidate`, exact: true }).click();
  await page.getByRole('button', { name: 'Approve candidate', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Review icon changes' })).toBeEnabled();
  await expect(page.locator('.icon-previews img')).toHaveCount(10);
  for (const image of await page.locator('.icon-previews img').all()) await expect(image).toHaveJSProperty('naturalWidth', 1024);
  await openIconSettings(page); await page.getByRole('button', { name: 'Review icon changes' }).click();
  await expect(page.getByRole('heading', { name: 'Proposed app.json change' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Confirm and apply icon' })).toBeDisabled();
  expect((await engine.files.read(projectId, 'app.json')).content).toBe(originalConfig.content);
  await page.getByRole('button', { name: 'Cancel config proposal' }).click();
  await expect(page.getByRole('heading', { name: 'Proposed app.json change' })).toHaveCount(0);
  await openIconSettings(page); await page.getByRole('button', { name: 'Review icon changes' }).click();
  await expect(page.getByRole('heading', { name: 'Proposed app.json change' })).toBeVisible();
  await engine.files.write(projectId, [{ path: 'app.json', expectedRevision: originalConfig.revision, content: originalConfig.content + '\n' }]);
  await page.getByRole('checkbox', { name: 'I reviewed this exact config change and want to apply it.' }).check();
  await page.getByRole('button', { name: 'Confirm and apply icon' }).click();
  const failedProposal = page.getByRole('dialog', { name: 'Proposed app.json change' });
  await expect(failedProposal).toBeVisible();
  await expect(failedProposal.getByRole('alert')).toContainText('Icon or config changed');
  await expect(failedProposal.getByRole('checkbox')).not.toBeChecked();
  await expect(failedProposal.getByRole('button', { name: 'Confirm and apply icon' })).toBeDisabled();
  expect((await engine.files.read(projectId, 'app.json')).content).toBe(originalConfig.content + '\n');
  await failedProposal.getByRole('button', { name: 'Cancel config proposal' }).click();
  await expect(page.getByRole('button', { name: 'Review icon changes' })).toBeFocused();
  await openIconSettings(page); await page.getByRole('button', { name: 'Review icon changes' }).click();
  await expect(page.getByRole('checkbox', { name: 'I reviewed this exact config change and want to apply it.' })).not.toBeChecked();
  await page.getByRole('checkbox', { name: 'I reviewed this exact config change and want to apply it.' }).check();
  await page.getByRole('button', { name: 'Confirm and apply icon' }).click();
  const library = await engine.assets.list(projectId), master = library.assets[1]!;
  await expect.poll(async () => JSON.parse((await engine.files.read(projectId, 'app.json')).content).expo.icon).toBe(`./${master.path}`);
  const before = JSON.parse(originalConfig.content).expo;
  expect(JSON.parse((await engine.files.read(projectId, 'app.json')).content).expo).toEqual({ ...before, icon: `./${master.path}` });
  for (const width of [375, 1440]) {
    await page.setViewportSize({ width, height: 1100 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect.poll(() => page.getByRole('region', { name: 'App icon workflow' }).locator('button:visible,input:not([type=checkbox]):visible,select:visible').evaluateAll(elements => elements.filter(el => { const b = el.getBoundingClientRect(); const minimum = matchMedia('(max-width: 760px), (pointer: coarse)').matches ? 44 : 36; return b.width < minimum || b.height < minimum; }).map(el => el.outerHTML))
    ).toEqual([]);
  }
});
