import { useEffect, useId, useRef, useState } from 'react';
import { ArrowUpRight, Check, ImagePlus, Palette, Sparkles, X } from 'lucide-react';
import { ASTRA_MODEL, IMAGE_MODEL, mediaModelSchema, type JobRequest } from '../../../../packages/core/src/media-job-contracts';
import type { AssistantStatus, MediaState, StudioState } from '../api';
import { creativePrompt, creativeSuggestionContext, creativePurposes, creativeStyles, type CreativeDraft, type CreativePurpose, type CreativeSeed, type CreativeStyle } from '../creative';
import { CreativeSuggestion } from './CreativeSuggestion';
import { AssetImage } from './AssetImage';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Textarea } from './ui/textarea';
import { FieldSelect } from './ui/field-select';

type Props = { projectId: string; data: MediaState; state?: StudioState; assistantStatus?: AssistantStatus; busy: boolean; active: boolean; iconOnly?: boolean; seed?: CreativeSeed; savedDraft?: CreativeDraft; onDraft?(draft: CreativeDraft): void; onClose(): void; onSettings(section?: 'images'): void; onStage(request: JobRequest): Promise<boolean> };
export function AssetGenerator({ projectId, data, state, assistantStatus, busy, active, iconOnly = false, seed, savedDraft, onDraft, onClose, onSettings, onStage }: Props) {
  const id = useId();
  const [draft, setDraft] = useState<CreativeDraft>(() => savedDraft ?? { model: data.capabilities.models.some(model => model.id === ASTRA_MODEL) ? ASTRA_MODEL : IMAGE_MODEL, operation: 'generate', referenceIds: [], quality: 'high', size: '1024x1024', count: 1, label: iconOnly ? 'New app icon' : 'New illustration', prompt: '', purpose: iconOnly ? 'app-icon' : 'illustration', style: iconOnly ? 'minimal' : 'art-direction', useAppDirection: true });
  const [advanced, setAdvanced] = useState(false);
  const draftListener = useRef(onDraft); draftListener.current = onDraft;
  useEffect(() => { draftListener.current?.(draft); }, [draft]);
  const update = (patch: Partial<CreativeDraft>) => setDraft(previous => ({ ...previous, ...patch }));
  useEffect(() => {
    if (!seed) return;
    setDraft(previous => ({ ...previous, referenceIds: [seed.referenceId], operation: 'edit', label: `${seed.label.slice(0, 85)} variation`, purpose: seed.role in creativePurposes ? seed.role as CreativePurpose : 'illustration', size: seed.role === 'app-icon' ? '1024x1024' : previous.size, prompt: `Create a fresh variation of ${seed.label}. Keep its subject and overall identity, with more refined lighting, material detail and composition.` }));
    setAdvanced(true);
  }, [seed]);
  const chatgptConnected = assistantStatus?.connections?.some(connection => connection.id === 'chatgpt' && connection.configured);
  const assistantConnected = assistantStatus?.available && assistantStatus.configured;
  const imageProvider = data.capabilities.provider;
  const design = state?.design && 'tokens' in state.design ? state.design : undefined;
  const purpose = creativePurposes[draft.purpose], prompt = creativePrompt(draft, data.brief, state);
  const references = data.assets.filter(asset => asset.status === 'approved');
  const invalidReferences = draft.referenceIds.some(ref => !references.some(asset => asset.id === ref));
  const modelAvailable = data.capabilities.models.some(model => model.id === draft.model);
  const valid = modelAvailable && draft.prompt.trim() && draft.label.trim() && prompt.length <= 8000 && !invalidReferences && (draft.operation !== 'edit' || draft.referenceIds.length > 0);
  if (!active) return null;
  return <form hidden={!active} className="media-card creative-generator" aria-label={iconOnly ? 'Icon generation' : 'Image generation'} onSubmit={event => {
    event.preventDefault(); if (!valid || busy) return;
    void onStage({ requestId: crypto.randomUUID(), expectedRevision: data.revision, model: draft.model, operation: draft.operation, referenceIds: draft.referenceIds, quality: draft.quality, size: draft.size, count: draft.count, label: draft.label.trim(), role: purpose.role, rightsNote: '', prompt });
  }}>
    <div className="creative-heading"><div><span className="creative-eyebrow"><Sparkles size={14} aria-hidden />Create with AI</span><h2>{iconOnly ? 'An icon that feels like your app.' : 'Generate or edit'}</h2><p>{iconOnly ? 'One memorable mark. Built around your idea and your visual style.' : 'From a rough idea to artwork that belongs in your app.'}</p></div><Button variant="ghost" aria-label="Close generation" title="Close generation" onClick={onClose}><X aria-hidden /></Button></div>
    <fieldset className="creative-fields" disabled={busy}>
      {data.capabilities.provider.source === 'managed' && data.capabilities.models.some(model => model.id === IMAGE_MODEL) && !data.capabilities.models.some(model => model.id === ASTRA_MODEL) && <p>Included credits use GPT Image direct. Astra-assisted images require a personal image key selected in Settings.</p>}
      {!modelAvailable && <p role="alert">Your draft’s model is unavailable with the selected connection. Choose a model in advanced settings or explicitly select a personal image key. Your draft has not been changed.</p>}
      {!iconOnly && <div className="creative-purpose-grid" role="group" aria-label="Asset type">{Object.entries(creativePurposes).map(([key, value]) => <button type="button" key={key} aria-pressed={draft.purpose === key} onClick={() => update({ purpose: key as CreativePurpose, size: value.size, label: `New ${value.label.toLowerCase()}` })}><span className={`creative-purpose-symbol ${key}`} aria-hidden><ImagePlus size={18} /></span><strong>{value.label}</strong><small>{value.subtitle}</small></button>)}</div>}
      <div className="creative-main"><div className="creative-description"><Label htmlFor={`${id}-prompt`}>{iconOnly ? 'Describe your icon' : 'What should we create?'}</Label><Textarea id={`${id}-prompt`} aria-label="Image prompt" required maxLength={7000} rows={4} placeholder={purpose.starter} value={draft.prompt} onChange={event => update({ prompt: event.target.value })} /><CreativeSuggestion projectId={projectId} appName={state?.project.name ?? "your app"} context={creativeSuggestionContext(draft, data.brief, state)} disabled={busy} onUse={prompt => update({ prompt })} onSettings={() => onSettings()} /></div>
      <div className="creative-style-section"><Label>Visual style</Label><div className="creative-styles" role="group" aria-label="Visual style">{Object.entries(creativeStyles).map(([key, value]) => <button type="button" key={key} className={`creative-style ${key}`} aria-pressed={draft.style === key} onClick={() => update({ style: key as CreativeStyle })}><span className="creative-style-swatch" aria-hidden><i /><b />{draft.style === key && <Check size={13} />}</span><span>{value.label}</span></button>)}</div></div></div>
      <div className="creative-direction"><Palette size={18} aria-hidden /><div><Label className="consent"><input type="checkbox" checked={draft.useAppDirection} onChange={event => update({ useAppDirection: event.target.checked })} />Match my app’s art direction</Label><p>{draft.useAppDirection ? 'Includes your saved brief and interface palette in the reviewed prompt.' : 'Create a fresh direction, independent of your app’s palette.'}</p>{draft.useAppDirection && design && <div className="creative-palette" aria-label="App palette">{[design.tokens.accent, design.tokens.background, design.tokens.surface, design.tokens.text].map((color, index) => <span key={index} title={color} style={{ background: color }} />)}<small>{data.brief.mood || design.preset}</small></div>}</div></div>
      <div className="creative-output"><FieldSelect label="Quality" value={draft.quality} disabled={busy} onValueChange={value => update({ quality: value as JobRequest['quality'] })} options={[{ value: 'high', label: 'High · finest detail' }, { value: 'medium', label: 'Medium · balanced' }, { value: 'low', label: 'Low · quick exploration' }]} /><FieldSelect label="Output size" value={draft.size} disabled={busy || iconOnly || draft.purpose === 'app-icon'} onValueChange={value => update({ size: value as JobRequest['size'] })} options={[{ value: '1024x1024', label: 'Square · 1024 × 1024' }, { value: '1536x1024', label: 'Landscape · 1536 × 1024' }, { value: '1024x1536', label: 'Portrait · 1024 × 1536' }]} /></div>
      <details className="creative-options" open={advanced} onToggle={event => setAdvanced(event.currentTarget.open)}><summary>References & advanced settings{draft.referenceIds.length ? ` · ${draft.referenceIds.length} selected` : ''}</summary><div className="creative-advanced-fields"><Label htmlFor={`${id}-label`}>Request label<Input id={`${id}-label`} required maxLength={100} value={draft.label} onChange={event => update({ label: event.target.value })} /></Label><div className="media-fields"><FieldSelect label="Generation model" value={draft.model} disabled={busy} onValueChange={value => { const model = mediaModelSchema.parse(value); update({ model, count: model === ASTRA_MODEL ? 1 : draft.count }); }} options={data.capabilities.models.map(model => ({ value: model.id, label: model.label }))} /><FieldSelect label="Operation" value={draft.operation} disabled={busy} onValueChange={value => update({ operation: value as JobRequest['operation'] })} options={[{ value: 'generate', label: 'Generate' }, { value: 'edit', label: 'Edit approved image' }]} /><FieldSelect label="Candidates" value={String(draft.count)} disabled={busy} onValueChange={value => update({ count: Number(value) })} options={(draft.model === ASTRA_MODEL ? ['1'] : ['1', '2']).map(value => ({ value, label: value }))} /></div>
      <div className="creative-references"><p>Reference images · {draft.referenceIds.length} of 4 selected</p><small>Only selected images are sent. For an edit, the first selected image is the source.</small>{!references.length && <p>Approve an image in your library to use it as a reference.</p>}<div>{references.map(asset => <label key={asset.id}><input type="checkbox" aria-label={asset.label} checked={draft.referenceIds.includes(asset.id)} disabled={busy || (!draft.referenceIds.includes(asset.id) && draft.referenceIds.length >= 4)} onChange={event => update({ referenceIds: event.target.checked ? [...draft.referenceIds, asset.id] : draft.referenceIds.filter(id => id !== asset.id) })} /><AssetImage projectId={projectId} asset={asset} /><span>{asset.label}</span></label>)}</div>{invalidReferences && <p role="alert">A selected reference is no longer available. Choose references again.</p>}</div></div></details>
      {draft.prompt.trim() && <details className="creative-prompt-preview"><summary>Preview full creative prompt <span>{prompt.length.toLocaleString()} / 8,000</span></summary><pre>{prompt}</pre></details>}
      {prompt.length > 8000 && <p role="alert">The combined prompt is too long. Shorten your description or turn off app art direction.</p>}
      {!data.capabilities.available && <section className="creative-connect" aria-label="Image generation setup"><div><strong>{chatgptConnected ? 'ChatGPT is connected' : assistantConnected ? `${assistantStatus.provider ?? 'Your Assistant'} is connected` : 'Set up image generation'}</strong><p>{chatgptConnected ? 'Your ChatGPT sign-in supports Assistant and Suggest. ' : assistantConnected ? 'Your Assistant connection supports chat and suggestions. ' : ''}{imageProvider.configured ? data.capabilities.reason || 'Image generation is unavailable with the current settings.' : imageProvider.managed ? `To create images here, choose ${imageProvider.managed.label} or add an OpenAI API key in image settings.` : 'Creating images in Dunara currently requires an OpenAI API key, with API usage billed separately from ChatGPT.'}</p></div><Button variant="outline" onClick={() => onSettings('images')}>{imageProvider.configured ? 'Review image settings' : 'Set up image generation'}<ArrowUpRight size={14} aria-hidden /></Button></section>}
    </fieldset><footer className="creative-footer">
      <div className="creative-submit"><div><strong>{draft.model === ASTRA_MODEL ? 'Astra + GPT Image' : 'GPT Image direct'}</strong><small>{draft.quality === 'high' ? 'High quality' : draft.quality === 'medium' ? 'Balanced quality' : 'Quick exploration'} · {draft.count} {draft.count === 1 ? 'image' : 'images'} · PNG</small></div><Button type="submit" disabled={busy || !valid}><Sparkles size={16} aria-hidden />Stage request for review</Button></div><p className="creative-cost-note">Review the exact prompt and settings next. Generation starts only after you approve the paid request.</p>
    </footer>
  </form>;
}
