import { randomUUID } from 'node:crypto';
import { mkdtemp, readFile, rm, writeFile, symlink, cp } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, expect, it } from 'vitest';
import { Projects, projectMetadataFile } from './projects.js';
import { Engine } from './engine.js';
import type { StudioAction } from './studio-contracts.js';
let dir: string, engine: Engine;
beforeEach(async () => { dir = await mkdtemp(path.join(os.tmpdir(), 'builder-control-')); engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false); });
afterEach(async () => { await engine.close(); await rm(dir, { recursive: true, force: true }); });
async function act(action: StudioAction) { return engine.studio.control({ expectedRevision: (await engine.studio.snapshot()).revision, action }); }
it('persists project identity and shared preferences but never runtime state or approvals', async () => {
  const project = await engine.projects.create({ name: 'Érable', slug: 'erable' });
  const other = await engine.projects.create({ name: 'Other', slug: 'other' });
  const file = path.join(project.root, projectMetadataFile);
  const initial = JSON.parse(await readFile(file, 'utf8'));
  expect(initial.project.id).toBe(project.id); expect(initial.project).not.toHaveProperty('root');
  await act({ type: 'select-project', projectId: other.id }); await act({ type: 'select-project', projectId: project.id });
  const id = randomUUID(); await act({ type: 'add', id }); await act({ type: 'update', id, patch: { route: '/habit', viewport: 'large' } });
  await act({ type: 'reload', id }); await act({ type: 'design', open: true }); await act({ type: 'assets-tab', tab: 'launch-kit' });
  const current = await engine.studio.snapshot(); expect(current.studio?.board.views[1]?.refresh).toBe(1);
  const saved = await readFile(file, 'utf8'); expect(saved).not.toMatch(/refresh|token|credential|approval|localhost|root/);
  await engine.close(); engine = new Engine(await Projects.open(engine.projects.workspace, engine.projects.home), false);
  const restored = await engine.studio.snapshot();
  expect(restored.projectId).toBe(project.id); expect(restored.studio).toMatchObject({ workspace: 'assets', assetsTab: 'launch-kit', designOpen: true, board: { activeId: id } });
  expect(restored.studio?.board.views[1]).toMatchObject({ route: '/habit', viewport: 'large', refresh: 0 });
  expect(restored.revision).not.toBe(current.revision); expect(engine.previews.status(project.id).status).toBe('stopped');
  expect(engine.captures.list(project.id)).toEqual([]);
});
it('serializes competing revisions, bounds views and rejects unsafe control input', async () => {
  await engine.projects.create({ name: 'Control', slug: 'control' });
  const current = await engine.studio.snapshot();
  const results = await Promise.allSettled(['assets', 'activity'].map(workspace => engine.studio.control({ expectedRevision: current.revision, action: { type: 'navigate', workspace } })));
  expect(results.filter(r => r.status === 'fulfilled')).toHaveLength(1); expect(results.filter(r => r.status === 'rejected')).toHaveLength(1);
  const id = randomUUID(); await act({ type: 'add', id }); await expect(act({ type: 'add', id: randomUUID() })).rejects.toMatchObject({ code: 'LIMIT_EXCEEDED' });
  await expect(act({ type: 'update', id, patch: { route: 'https://example.test/' } })).rejects.toThrow();
  await expect(act({ type: 'activate', id: randomUUID() })).rejects.toThrow();
  await expect(engine.studio.control({ expectedRevision: (await engine.studio.snapshot()).revision, action: { type: 'navigate', workspace: 'settings', token: 'forbidden' } })).rejects.toThrow();
  await act({ type: 'remove', id }); await expect(act({ type: 'remove', id: (await engine.studio.snapshot()).studio!.board.activeId })).rejects.toThrow();
});
it('remembers a portable project in a fresh registry and rejects conflicting identity or unsafe metadata', async () => {
  const project = await engine.projects.create({ name: 'Portable', slug: 'portable' });
  const registry = await Projects.open(engine.projects.workspace, path.join(dir, 'fresh-home'));
  expect(await registry.list()).toEqual([]); expect(await registry.register(project.slug)).toEqual(project);
  expect(await registry.register(project.slug)).toEqual(project); expect(await registry.list()).toHaveLength(1);
  await expect(registry.register('../home')).rejects.toThrow();
  const file = path.join(project.root, projectMetadataFile), original = await readFile(file, 'utf8');
  await writeFile(file, JSON.stringify({ ...JSON.parse(original), credentials: 'not allowed' })); await expect(registry.metadata(project)).rejects.toThrow();
  await writeFile(file, '{bad'); await expect(registry.metadata(project)).rejects.toThrow();
  await writeFile(file, 'x'.repeat(16_385)); await expect(registry.metadata(project)).rejects.toThrow();
  await rm(file); await writeFile(path.join(dir, 'outside.json'), original); await symlink(path.join(dir, 'outside.json'), file);
  await expect(registry.metadata(project)).rejects.toThrow(); await expect(registry.register(project.slug)).rejects.toThrow();
  await rm(file); await writeFile(file, original);
  await cp(project.root, path.join(engine.projects.workspace, 'duplicate'), { recursive: true });
  const duplicate = JSON.parse(original); duplicate.project.slug = 'duplicate';
  await writeFile(path.join(engine.projects.workspace, 'duplicate', projectMetadataFile), JSON.stringify(duplicate));
  await expect(registry.register('duplicate')).rejects.toThrow();
});
it('reads legacy projects without mutation and creates metadata on an explicit control', async () => {
  const project = await engine.projects.create({ name: 'Legacy', slug: 'legacy' }); const file = path.join(project.root, projectMetadataFile);
  await rm(file); expect((await engine.studio.snapshot()).projectId).toBe(project.id);
  await expect(readFile(file)).rejects.toMatchObject({ code: 'ENOENT' });
  await act({ type: 'navigate', workspace: 'activity' }); expect(JSON.parse(await readFile(file, 'utf8')).studio.workspace).toBe('activity');
  await expect(engine.files.read(project.id, projectMetadataFile)).rejects.toMatchObject({ code: 'INVALID_PATH' });
});

it('persists canvas modes and configures comparisons atomically without losing screen identities', async () => {
  const project = await engine.projects.create({ name: 'Canvas', slug: 'canvas' });
  const original = (await engine.studio.snapshot()).studio!.board.activeId;
  await act({ type: 'compare', comparison: 'sizes', route: '/habit' });
  let board = (await engine.studio.snapshot()).studio!.board;
  expect(board.views.map(view => [view.route, view.viewport])).toEqual([['/habit', 'compact'], ['/habit', 'large']]);
  expect(board.views[0]!.id).toBe(original);
  const otherId = board.views[1]!.id;
  await act({ type: 'update', id: otherId, patch: { route: '/progress' } });
  expect((await engine.studio.snapshot()).studio!.board.views.map(view => view.route)).toEqual(['/progress', '/progress']);
  await act({ type: 'canvas-mode', mode: 'overview' });
  await act({ type: 'focus-screen', route: '/' });
  await act({ type: 'canvas-mode', mode: 'compare' });
  expect((await engine.studio.snapshot()).studio!.board.views.map(view => [view.route, view.viewport])).toEqual([['/', 'compact'], ['/', 'large']]);
  await act({ type: 'compare', comparison: 'screens', route: '/', otherRoute: '/habit' });
  board = (await engine.studio.snapshot()).studio!.board;
  expect(board.views.map(view => view.id)).toEqual([original, otherId]);
  await engine.close(); engine = new Engine(await Projects.open(engine.projects.workspace, engine.projects.home), false);
  const restored = await engine.studio.snapshot();
  expect(restored.projectId).toBe(project.id);
  expect(restored.studio!.board).toMatchObject({ mode: 'compare', comparison: 'screens' });
  expect(restored.studio!.board.views.map(view => view.route)).toEqual(['/', '/habit']);
});
