import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import sharp from 'sharp';
import { z } from 'zod';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createMcpServer } from '../../mcp/src/server.js';
import { Engine } from '../../core/src/engine.js';
import { Projects } from '../../core/src/projects.js';
import { manifestSchema, MEDIA_BYTES } from '../../core/src/media-contracts.js';
import { startStudio } from './studio-server.js';
import { ASTRA_MODEL, IMAGE_MODEL } from '../../core/src/media-job-contracts.js';
let dir: string, engine: Engine, studio: Awaited<ReturnType<typeof startStudio>>, client: Client, server: ReturnType<typeof createMcpServer>;
let projectId: string, otherId: string, bytes: Buffer, headers: Record<string, string>;
const generate = vi.fn();
beforeEach(async () => {
  dir = await mkdtemp(path.join(os.tmpdir(), 'builder-media-api-'));
  bytes = await sharp({ create: { width: 48, height: 48, channels: 3, background: '#448866' } }).png().toBuffer(); generate.mockReset().mockResolvedValue([bytes]);
  engine = new Engine(await Projects.open(path.join(dir, 'apps'), path.join(dir, 'home')), false, false, { run: generate });
  projectId = (await engine.projects.create({ name: 'Media', slug: 'media' })).id;
  otherId = (await engine.projects.create({ name: 'Other', slug: 'other' })).id;
  studio = await startStudio(engine, path.resolve('dist/studio'));
  const auth = await fetch(`${studio.origin}/api/bootstrap`, { method: 'POST', headers: { Origin: studio.origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ ticket: new URL(studio.launchUrl).hash.slice(1) }) });
  headers = { Origin: studio.origin, Authorization: `Bearer ${(await auth.json()).token}`, 'Content-Type': 'application/json' };
  server = createMcpServer(engine); client = new Client({ name: 'media-parity-test', version: '1' });
  const [a, b] = InMemoryTransport.createLinkedPair(); await server.connect(a); await client.connect(b);
});
afterEach(async () => { await client.close(); await server.close(); await studio.close(); await engine.close(); await rm(dir, { recursive: true, force: true }); });
const endpoint = (suffix = '', id = projectId) => `${studio.origin}/api/projects/${id}/media${suffix}`;
const post = (suffix: string, data: unknown, id = projectId) => fetch(endpoint(suffix, id), { method: 'POST', headers, body: JSON.stringify(data) });
const metadata = () => ({ expectedRevision: null, mediaType: 'image/png', label: 'Imported', role: 'illustration', rightsNote: 'Original test image' });
const upload = (extra: Record<string, string> = {}, body = bytes) => fetch(endpoint('/import'), { method: 'POST', headers: { ...headers, 'Content-Type': 'image/png', 'X-Builder-Media': encodeURIComponent(JSON.stringify(metadata())), ...extra }, body: new Uint8Array(body) });
const librarySchema = manifestSchema.extend({ revision: z.string().nullable() }).strip();
it('shares imports, image resources, brief, approvals and transforms with a real MCP protocol client', async () => {
  const imported = await upload(); expect(imported.status).toBe(200);
  let state = librarySchema.parse(await imported.json()); const original = state.assets[0]!;
  const listed = await client.callTool({ name: 'media_list', arguments: { projectId } }); expect(librarySchema.parse(listed.structuredContent)).toEqual(state);
  const read = await client.readResource({ uri: `builder://projects/${projectId}/media/${original.id}` });
  const image = z.object({ blob: z.string() }).parse(read.contents[0]); expect(Buffer.from(image.blob, 'base64')).toEqual((await engine.assets.read(projectId, original.id)).bytes);
  const response = await fetch(endpoint(`/images/${original.id}`), { headers }); expect(response.headers.get('cache-control')).toBe('no-store'); expect(response.headers.get('content-type')).toBe('image/png');
  state = librarySchema.parse((await client.callTool({ name: 'media_approve', arguments: { projectId, input: { assetId: original.id, expectedRevision: state.revision } } })).structuredContent);
  state = librarySchema.parse(await (await post('/brief', { expectedRevision: state.revision, brief: { mood: 'Quiet botanical', referenceIds: [original.id] } })).json());
  expect(librarySchema.parse((await client.callTool({ name: 'media_list', arguments: { projectId } })).structuredContent).brief.mood).toBe('Quiet botanical');
  const result = await client.callTool({ name: 'media_transform', arguments: { projectId, input: { assetId: original.id, expectedRevision: state.revision, width: 32, height: 64, fit: 'contain' } } });
  expect(result.isError).not.toBe(true); state = librarySchema.parse(await (await fetch(endpoint(), { headers })).json());
  expect(state.assets[1]).toMatchObject({ parentId: original.id, width: 32, height: 64, status: 'candidate' });
  expect((await fetch(endpoint(`/images/${original.id}`, otherId), { headers })).status).toBe(400);
  expect((await client.callTool({ name: 'media_read', arguments: { projectId: otherId, assetId: original.id } })).isError).toBe(true);
  expect(generate).not.toHaveBeenCalled();
});
it('reads the library after job reconciliation so completed outputs cannot have an older revision', async () => {
  const listJobs = engine.mediaJobs.list.bind(engine.mediaJobs);
  vi.spyOn(engine.mediaJobs, 'list').mockImplementationOnce(async id => {
    await engine.assets.import(id, { expectedRevision: null, mediaType: 'image/png', label: 'Output saved during reconciliation' }, bytes);
    return listJobs(id);
  });
  const response = await fetch(endpoint(), { headers });
  expect(response.status).toBe(200);
  const snapshot = librarySchema.parse(await response.json());
  expect(snapshot).toEqual(await engine.assets.list(projectId));
  expect(snapshot.assets[0]?.label).toBe('Output saved during reconciliation');
  expect(generate).not.toHaveBeenCalled();
});
it.each([IMAGE_MODEL, ASTRA_MODEL])('stages %s agent requests without spending and allows approval only from authenticated Studio', async model => {
  const tools = (await client.listTools()).tools;
  expect(tools.find(t => t.name === 'media_request')?.annotations?.openWorldHint).toBe(true);
  expect(tools.map(t => t.name)).not.toContain('media_job_approve');
  const request = { model, requestId: randomUUID(), expectedRevision: null, prompt: 'Original tree', operation: 'generate', label: 'Tree' };
  const staged = await client.callTool({ name: 'media_request', arguments: { projectId, input: request } });
  const job = z.object({ id: z.uuid(), state: z.literal('awaiting-approval') }).parse(staged.structuredContent);
  expect(generate).not.toHaveBeenCalled();
  expect((await fetch(endpoint('/job-approve'), { method: 'POST', headers: { Origin: studio.origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ jobId: job.id }) })).status).toBe(401);
  expect((await post('/job-approve', { jobId: job.id, expectedConfigurationRevision: engine.mediaJobs.providerStatus().revision }, otherId)).status).toBe(400);
  expect((await post('/job-approve', { jobId: job.id, expectedConfigurationRevision: engine.mediaJobs.providerStatus().revision })).status).toBe(200);
  await vi.waitFor(async () => expect((await engine.mediaJobs.get(projectId, job.id)).state).toBe('succeeded'));
  expect(generate).toHaveBeenCalledTimes(1);
  expect((await client.callTool({ name: 'media_job', arguments: { projectId, jobId: job.id } })).structuredContent).toMatchObject({ state: 'succeeded' });
  expect((await post('/job-approve', { jobId: job.id, expectedConfigurationRevision: engine.mediaJobs.providerStatus().revision })).status).toBe(400);
});
it('preserves authentication, exact origin, MIME, binary limits and the existing JSON boundary', async () => {
  expect((await upload({ Authorization: '' })).status).toBe(401);
  expect((await upload({ Origin: 'https://hostile.example' })).status).toBe(403);
  expect((await upload({ 'Content-Type': 'image/jpeg' })).status).toBe(400);
  expect((await upload({ 'Content-Encoding': 'gzip' })).status).toBe(400);
  expect((await upload({}, Buffer.from('<svg/>'))).status).toBe(400);
  expect((await upload({}, Buffer.alloc(MEDIA_BYTES + 1))).status).toBe(400);
  const json = await post('/job-request', { prompt: 'x'.repeat(1_000_001) }); expect(json.status).toBe(400);
  expect((await engine.assets.list(projectId)).assets).toHaveLength(0); expect(generate).not.toHaveBeenCalled();
});
it('shares icon preparation and config review with MCP while enforcing confirmation and authorization', async () => {
  const imported = librarySchema.parse(await (await upload()).json());
  await post('/approve', { assetId: imported.assets[0]!.id, expectedRevision: imported.revision });
  let library = await engine.assets.list(projectId);
  const result = await client.callTool({ name: 'icon_prepare', arguments: { projectId, input: { assetId: library.assets[0]!.id, expectedRevision: library.revision, kind: 'master', fit: 'contain', background: '#ffffff' } } });
  expect(result.isError).not.toBe(true); library = librarySchema.parse(result.structuredContent);
  const master = library.assets[1]!;
  await post('/approve', { assetId: master.id, expectedRevision: library.revision });
  const selection = { masterId: master.id, background: '#ffffff' };
  const checked = await client.callTool({ name: 'icon_check', arguments: { projectId, input: { assetId: master.id } } });
  expect(checked.structuredContent).toMatchObject({ available: false });
  const proposal = await client.callTool({ name: 'icon_preview', arguments: { projectId, input: selection } });
  expect(proposal.isError).not.toBe(true);
  const diff = z.object({ expectedConfigRevision: z.string(), expectedMediaRevision: z.string(), proposedRevision: z.string(), after: z.string() }).parse(proposal.structuredContent);
  expect(await (await post('/icon-preview', selection)).json()).toMatchObject(diff);
  const confirmation = { ...selection, expectedConfigRevision: diff.expectedConfigRevision, expectedMediaRevision: diff.expectedMediaRevision, proposedRevision: diff.proposedRevision, confirmed: true };
  expect((await post('/icon-apply', { ...confirmation, confirmed: false })).status).toBe(400);
  expect((await fetch(endpoint('/icon-apply'), { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: studio.origin }, body: JSON.stringify(confirmation) })).status).toBe(401);
  expect((await post('/icon-apply', confirmation, otherId)).status).toBe(400);
  expect((await client.callTool({ name: 'icon_apply', arguments: { projectId, input: confirmation } })).isError).not.toBe(true);
  expect((await engine.files.read(projectId, 'app.json')).content).toBe(diff.after);
  expect(generate).not.toHaveBeenCalled();
});
